# Generated by Django 3.1.6 on 2021-02-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210213_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='issues',
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.project'),
            preserve_default=False,
        ),
    ]
