# Generated by Django 3.1.6 on 2021-02-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210214_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='reported',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pages.employee'),
            preserve_default=False,
        ),
    ]
