# Generated by Django 3.1.6 on 2021-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_issue_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('ASAP', 'ASAP'), ('Normal', 'Normal')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
