# Generated by Django 3.1.4 on 2021-03-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_issue_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profil_pic',
            field=models.ImageField(blank=True, upload_to='profileImg/'),
        ),
    ]
