# Generated by Django 3.1.4 on 2021-03-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
