# Generated by Django 3.1.4 on 2021-03-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210302_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='docs/issues'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='docs/projects'),
        ),
    ]
